/** Katalog tipe Smart Jurnal — aman di-import komponen client. */
export const smartJurnalTipe = [
  "BEBAN_OPERASIONAL",
  "PRIVE",
  "SUNTIKAN_MODAL",
  "TRANSFER_KAS",
  "PINJAMAN_MASUK",
  "BAYAR_HUTANG",
  "BELI_ASET_TUNAI",
  "BAYAR_BUNGA",
  "PENYUSUTAN_GREENHOUSE",
  "PENYUSUTAN_INSTALASI",
  "PEMBELIAN_BAHAN_TUNAI",
  "PEMBELIAN_BAHAN_KREDIT",
  "PENDAPATAN_LAIN",
  "GAJI_PETANI",
  "TERIMA_PIUTANG",
  "BEBAN_PENGIRIMAN",
  "BELI_BENIH_TUNAI",
] as const;
export type SmartJurnalTipe = (typeof smartJurnalTipe)[number];

export const smartJurnalTipeLabel: Record<SmartJurnalTipe, string> = {
  BEBAN_OPERASIONAL: "Beban operasional (5230)",
  PRIVE: "Prive pemilik (3200)",
  SUNTIKAN_MODAL: "Suntikan modal (3100)",
  TRANSFER_KAS: "Transfer antar kas/bank",
  PINJAMAN_MASUK: "Pinjaman masuk (Dr kas · Cr hutang)",
  BAYAR_HUTANG: "Bayar hutang usaha (2100)",
  BELI_ASET_TUNAI: "Beli aset tunai (1500 greenhouse)",
  BAYAR_BUNGA: "Beban bunga pinjaman (5500)",
  PENYUSUTAN_GREENHOUSE: "Penyusutan greenhouse (5210 · 1510)",
  PENYUSUTAN_INSTALASI: "Penyusutan instalasi listrik (5220 · 1530)",
  PEMBELIAN_BAHAN_TUNAI: "Beli nutrisi/bahan tunai (1330)",
  PEMBELIAN_BAHAN_KREDIT: "Beli nutrisi/bahan kredit (1330 · 2100)",
  PENDAPATAN_LAIN: "Pendapatan lain (4100)",
  GAJI_PETANI: "Gaji petani (5200)",
  TERIMA_PIUTANG: "Terima piutang (Dr kas · Cr 1200)",
  BEBAN_PENGIRIMAN: "Beban pengiriman (5400)",
  BELI_BENIH_TUNAI: "Beli benih tunai (1310)",
};
